org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
minecraft_version=1.21.1
minecraft_version_range=[1.21.1 ,1.22)
neo_version=21.1.143
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties

mod_id=spells_gone_wrong
mod_name=Spells Gone Wrong
mod_license=All Rights Reserved
mod_version=1.21.1-2.0.0
mod_group_id=com.kekecreations.spells_gone_wrong
mod_authors=KekeCreations
mod_description=This mod allows you to take damage from your own casted spells and configure new spell features. Only works on spells added by Iron's Spells N Spellbooks [Configurable]



#Mod Dependencies
caelus_version=7.0.0+1.21
geckolib_version=4.7.5.1
player_animator_version=2.0.0-alpha1+1.21
