modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="spells_gone_wrong" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Spells Gone Wrong" #mandatory
logoFile="examplemod.png" #optional
credits="A Special thanks to dreadnews on Discord for the mod idea. This mod was originally going to be a commission for dreadnews on Discord but I loved the mod idea and wanted to make it super configurable so I decided to make it for free and upload it for everyone else!" #optional
authors="KekeCreations" #optional
description='''
This mod allows you to take damage from your own casted spells. Only works on spells added by Iron's Spells N Spellbooks [Highly configurable]
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.spells_gone_wrong]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.spells_gone_wrong]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
